require('edit.dashboard-nvim')
require('edit.autopairs')
require('edit.neoscroll')
require('edit.todo')
require('edit.translate')
require('edit.bookmark')
require('edit.fcitx5')
require('edit.nvim-tree')
require('edit.comment')
require('edit.asyncrun')
require('edit.fold')
require('edit.bufferline')
require('edit.which-key')
require('edit.themer')
require('edit.venn')
require('edit.status-line')
-- require('edit.marks')
-- require('edit.rainbow')
-- require('edit.status-line')
-- require('edit.neogit')
-- require('edit.cursorline')
-- require('edit.refactoring')
