require('setup')
require('theme')

require('imselect')
require('lsp.init')
require('lang.init')
require('completion.init')
require('debugger.init')
require('tools.init')
require('edit.init')
require('menu.init')
require('keymap')
require('menu.wilder')
